### PR TITLE
Atom is back

### PR DESCRIPTION
**Pull request by MicroNovaX**
### 1. Why is this change necessary?
Because atom is now development

### 2. What does this change do, exactly?
Change status atom.

### 6. Checklist

- [+] I have written tests and verified that they fail without my change
- [+] I have squashed any insignificant commits
- [+] This change has comments for package types, values, functions, and non-obvious lines of code
- [+] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by GMatrixGames** [comment]
All I have to say is, it shouldn't be recommended tbh

**Comment by MicroNovaX** [comment]
> All I have to say is, it shouldn't be recommended tbh

This sounds very funny given that your fork is a complete copy of the atom. 
Good luck in stealing someone else's commits and changing your copyright.

**Comment by GMatrixGames** [comment]
Sure, say what you will, but I had permission, so stop being salty and leave it be.

**Comment by GMatrixGames** [comment]
> I will not be responding anymore, so I really don't care anymore

**Pull request merged**
